### ISSUE TITLE
这个框架只能同时创建一个socket吗？

### ISSUE THREAD

**Issue by ChenLin-Wang** [skynetlua/mushroom#2]
如题。我看到在这个框架中这个socket变量是作为唯一全局变量定义的。也就是说不能同时创建多个socket以处理更多任务？

**Comment by skynetlua** [comment]
不需要的，就这个socket，就可以创建多个socket 进行listen。此项目废弃，请使用OpenSocket项目，在win32支持IOCP 请见https://github.com/openlinyou/opensocket
